travel_blog:
    resource: "@TravelBlogBundle/Resources/config/routing.yml"
    prefix:   /

grd_blog:
    resource: "@GrdBlogBundle/Controller/"
    type:     annotation
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
